### ISSUE TITLE
Running on Raspberry Pi Raspbian

### ISSUE THREAD

**Issue by BracWebb** [cgrossde/Pullover#103]
Does the Linux version work on Raspbian for Raspberry Pis? I get the following:
```
pi@rpi:~/pullover $ ./pullover 
bash: ./pullover: cannot execute binary file: Exec format error
```
The notification library, `libnotify4`, is installed per the following documents:

- https://github.com/cgrossde/Pullover/wiki/Installing-on-Linux
- https://github.com/cgrossde/Pullover/issues/24

Is this an OS compatibility issue, something else, or something I am doing wrong? Thanks!

**Comment by frebib** [comment]
Probably because Raspberry Pi is arm architecture, not the standard x86 that most desktop computers to run. Fortunately, this is open source so you can just recompile it for your architecture!

**Comment by cgrossde** [comment]
Thank you @frebib. I don't support Raspbian and will close this ticket.
