### ISSUE TITLE
fatal error - no network?

### ISSUE THREAD

**Issue by boneskull** [cgrossde/Pullover#104]
I got the "fatal error, report a bug" dialog.

[Here's the logfile](https://gist.github.com/boneskull/41333bc1c8a4afa3c5f5afc4ab606f8e) you asked for.

I may have disconnected, reconnected, put the machine to sleep, changed networks, and/or been connected to *multiple* networks whenever this was happening.

**Comment by fnordpojk** [comment]
I just had the same issue:

Tue Oct 03 2017 17:48:18 GMT+0200 (W. Europe Daylight Time)  ConnectionManager    'Connect to WebSocket'
Tue Oct 03 2017 17:48:22 GMT+0200 (W. Europe Daylight Time)  PushoverWSClient     'Connected'
Tue Oct 03 2017 17:55:41 GMT+0200 (W. Europe Daylight Time)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Tue Oct 03 2017 17:55:41 GMT+0200 (W. Europe Daylight Time)  Fatal                'Pullover v1.2.0'
Tue Oct 03 2017 17:55:41 GMT+0200 (W. Europe Daylight Time)  Fatal                '=============== STACK ==============='
Tue Oct 03 2017 17:55:41 GMT+0200 (W. Europe Daylight Time)  Fatal                'Error: read ECONNRESET
    at exports._errnoException (util.js:734:11)
    at TCP.onread (net.js:531:26)'
Tue Oct 03 2017 17:55:41 GMT+0200 (W. Europe Daylight Time)  Fatal                '=============== Error Object ==============='
Tue Oct 03 2017 17:55:41 GMT+0200 (W. Europe Daylight Time)  Fatal                '{
    stack: 'Error: read ECONNRESET
    at exports._errnoException (util.js:734:11)
    at TCP.onread (net.js:531:26)',
    message: 'read ECONNRESET',
    code: 'ECONNRESET',
    errno: 'ECONNRESET',
    syscall: 'read'
}'
Tue Oct 03 2017 17:55:41 GMT+0200 (W. Europe Daylight Time)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Tue Oct 03 2017 17:55:41 GMT+0200 (W. Europe Daylight Time)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Tue Oct 03 2017 17:55:41 GMT+0200 (W. Europe Daylight Time)  Fatal                'Pullover v1.2.0'
Tue Oct 03 2017 17:55:41 GMT+0200 (W. Europe Daylight Time)  Fatal                '=============== STACK ==============='
Tue Oct 03 2017 17:55:41 GMT+0200 (W. Europe Daylight Time)  Fatal                'Error: socket hang up
    at createHangUpError (_http_client.js:192:15)
    at TLSSocket.socketCloseListener (_http_client.js:224:23)
    at emitOne (events.js:80:20)
    at TLSSocket.emit (events.js:150:7)
    at TCP.close (net.js:457:12)'
Tue Oct 03 2017 17:55:41 GMT+0200 (W. Europe Daylight Time)  Fatal                '=============== Error Object ==============='
Tue Oct 03 2017 17:55:41 GMT+0200 (W. Europe Daylight Time)  Fatal                '{ stack: 'Error: socket hang up
    at createHangUpError (_http_client.js:192:15)
    at TLSSocket.socketCloseListener (_http_client.js:224:23)
    at emitOne (events.js:80:20)
    at TLSSocket.emit (events.js:150:7)
    at TCP.close (net.js:457:12)', message: 'socket hang up', code: 'ECONNRESET' }'
Tue Oct 03 2017 17:55:41 GMT+0200 (W. Europe Daylight Time)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '

This appears to be #63 - may want to merge this into that instead.

**Comment by cgrossde** [comment]
Thank you for reporting this issue, I will track it in #106
