### ISSUE TITLE
Can't Change Default Notification Sound

### ISSUE THREAD

**Issue by cyberfunk** [cgrossde/Pullover#105]
I switched the default notification sound to the luxurious and calming Piano Bar sound but my alert is an ugly Fire Truck horn that is very upsetting. I've also chosen "Use native notifications" if that helps. How can I change the sound permanently to Piano Bar? Also how do I clear recent notifications from the list. All I can see is a bar at the top that says Refresh. I'd like to be able to clear the alerts manually if possible. Any help is much appreciated.

**Comment by bryanscottwalker** [comment]
cyberfunk, are all of your notifications coming from one source? If the sending client has the sound set to the fire truck horn, then it will override your selection.

**Comment by cgrossde** [comment]
@bryanscottwalker is right. However I added an option in the new alpha do disable sounds completely:
[1.3.0-alpha.1](https://github.com/cgrossde/Pullover/releases/tag/1.3.0-alpha.1)
There is no option at the moment to clear notifications from the list.
Will close this issue for now, feel free to reopen it.
