### ISSUE TITLE
Notification sounds aren't necessarily useful on desktop...

### ISSUE THREAD

**Issue by bryanscottwalker** [cgrossde/Pullover#109]
Notification sounds on desktop can be overly loud, especially if you keep the system volume at max and use volume controls built into programs for that purpose. As I don't have any system sounds that play (I find them annoying) I have exactly this setup.

On a mobile phone in my pocket, these sounds are great. On my desktop where I can see the toast, not as much, and considering the volume is up high, extremely jarring.

Can a method be built in where the Pullover client ignores all sound items and simply is set to silent at all times, or plays a singular sound regardless of the sending client's wishes?  (This could be an silent .wav for my purposes.)

**Comment by cgrossde** [comment]
You can select the notification sound "None" in the soundlist. Will make this setting clearer in the next version
