### ISSUE TITLE
No "popups" on Win 10

### ISSUE THREAD

**Issue by jonferreira** [cgrossde/Pullover#110]
Hi,

I'm runing 1.2 on Windows 10 and even though it "works", i.e. sounds the notification and notifications are displayed on the app itself, I don't have any "popup" or flyout. I've tried both with and without the Use Native Notifications setting enabled.

Any ideas?

**Comment by nerdtechse** [comment]
I have the same problem. It came after windows 10 Fall Creators Update.  I seen other programs have the same problem.. https://github.com/meetfranz/franz/issues/173 https://github.com/electron/electron/issues/10864

**Comment by jonferreira** [comment]
oh dear...at least I'm not alone but doesn't sound like something with an easy fix.

**Comment by alexmoyag** [comment]
I have the same issue too!!!!

**Comment by apbirch67** [comment]
Same issue here, no popup after Fall Creators update.  I'm seeing the same issue with another tool that we use.

**Comment by egooner** [comment]
Same problem here. Looking in the log I can see the notification is coming in but nothing visible on Windows 10

**Comment by twister5800** [comment]
Also same issue :-)

**Comment by cgrossde** [comment]
Please try the new alpha, it should be fixed there: [1.3.0-alpha.1](https://github.com/cgrossde/Pullover/releases/tag/1.3.0-alpha.1)

**Comment by ersan** [comment]
Is there no way to get native notifications working again?  I used Pullover specifically because it supported native Windows 10 notifications.
