### ISSUE TITLE
Pullover Crashing Upon Opening

### ISSUE THREAD

**Issue by MajorPlans** [cgrossde/Pullover#113]
It's set to open when I login to my computer...lately it's been crashing upon opening.

**Comment by cgrossde** [comment]
@MajorPlans Please provide the logs, which version are you using, which OS? Could you try the new version [1.3.0-alpha.1](https://github.com/cgrossde/Pullover/releases/tag/1.3.0-alpha.1) and check if the problem persists?

**Comment by cgrossde** [comment]
Will close, please reopen if the  problem persists in version 1.3.0
