### ISSUE TITLE
Doesn't notify you when disconnected

### ISSUE THREAD

**Issue by mastermood** [cgrossde/Pullover#114]
This application has shown a status of "OFFLINE" several times now while the internet is running & you have no way of knowing unless you check manually. 

See: https://i.snag.gy/DxzTiP.jpg

There **_should be_** a popup indicator that tells you when it is no longer connected, & also allow **_for auto-reconnect should it disconnect._** 

This is a major issue because one may miss major alerts simply because Pullover is disconnected. I have seen this happen several times now. 

Another useful feature would be to hover over the tray icon in the top menu bar (at least on Mac), & a little preview (without clicking) that shows connection status would be useful.

**From log file:**
_"Fri Mar 30 2018 19:42:55 GMT-0400 (EDT)  ConnectionManager    'Fetch failed - offline'   { [FetchNotificationsFailed: Fetch notification request failed]
  name: 'FetchNotificationsFailed',
  cause: 
   { [Error: connect ETIMEDOUT 207.244.109.177:443]
     code: 'ETIMEDOUT',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '207.244.109.177',
     port: 443 } }
Fri Mar 30 2018 19:42:55 GMT-0400 (EDT)  ConnectionManager    'Offline'
Fri Mar 30 2018 19:42:55 GMT-0400 (EDT)  PushoverWSClient     'Socket closed'
Fri Mar 30 2018 19:43:25 GMT-0400 (EDT)  ConnectionManager    'Checking internet connection'
Fri Mar 30 2018 19:43:55 GMT-0400 (EDT)  ConnectionManager    'Checking internet connection'
Fri Mar 30 2018 19:44:25 GMT-0400 (EDT)  ConnectionManager    'Checking internet connection'
Fri Mar 30 2018 19:44:55 GMT-0400 (EDT)  ConnectionManager    'Checking internet connection'
Fri Mar 30 2018 19:45:25 GMT-0400 (EDT)  ConnectionManager    'Checking internet connection'
Fri Mar 30 2018 19:45:55 GMT-0400 (EDT)  ConnectionManager    'Checking internet connection'
Fri Mar 30 2018 19:46:25 GMT-0400 (EDT)  ConnectionManager    'Checking internet connection'
Fri Mar 30 2018 19:46:55 GMT-0400 (EDT)  ConnectionManager    'Checking internet connection'
Fri Mar 30 2018 19:47:25 GMT-0400 (EDT)  ConnectionManager    'Checking internet connection'
Fri Mar 30 2018 19:47:55 GMT-0400 (EDT)  ConnectionManager    'Checking internet connection'
Fri Mar 30 2018 19:48:25 GMT-0400 (EDT)  ConnectionManager    'Checking internet connection'
Fri Mar 30 2018 19:48:55 GMT-0400 (EDT)  ConnectionManager    'Checking internet connection'
Fri Mar 30 2018 19:49:25 GMT-0400 (EDT)  ConnectionManager    'Checking internet connection'
Fri Mar 30 2018 19:49:55 GMT-0400 (EDT)  ConnectionManager    'Checking internet connection'"_

**Comment by cgrossde** [comment]
@mastermood Thanks for your report. I have a few questions:
* Which OS and version of Pullover are you using?
* Are you in a corporate network?

Pullover **does auto-reconnect** when:
* The notebook wakes from sleep
* When the internet connection is reestablished

I think the mechanism to detect if internet is available doesn't work on your machine. My guess is, that you are in a corporate network that filters certain packets and breaks the internet connection check feature of Pullover.

**Comment by mastermood** [comment]
I'm not on corporate, just home network. MacOS 10.12.6, no VPN, no firewall. Restarting Pullover will treat the problem. 

Is it possible a popup notification comes up if it gets disconnected? And also hovering over the tray bar icon showing the status like this: https://snag.gy/9O37uZ.jpg ?
