### ISSUE TITLE
display time Push message

### ISSUE THREAD

**Issue by dilowach** [cgrossde/Pullover#116]
Hi,

using Windows 10, received message is shown only for a few seconds !

How can I set the Pullover software to show the message in focus permanently until do a click to close ?

for information (found in 'console drawer'):

LOG PATH:  C:\Users\user\AppData\Roaming\Pullover\logs
debug.js:57   Settings             'Settings loaded'   { windowWidth: 450,
  windowHeight: 330,
  displayTime: 7,
  maxNotificationAmount: 20,
  runOnStartup: false,
  defaultSound: 'po',
  collectAnonymousData: null }

regards
dilowach

**Comment by cgrossde** [comment]
Sorry not possible, the display time is fixed by NW.js
