### ISSUE TITLE
Fatal error occured

### ISSUE THREAD

**Issue by online-stuff** [cgrossde/Pullover#117]
Fatal error occured
Sorry, something unexpected happened.

Please report this bug here together with the Pullover log file:
C:\Users\kevin\AppData\Roaming\Pullover\logs\pullover.1.log
Click to open the log file folder.
Please also add the Pullover version(1.2.0) and the operating system you were using.It is recommended to restart Pullover now

---------------------------------------------------------------------------------
OS Wndows 7 x64 SP1 - Most of the updates are done.

Has been going on for a couple weeks now.  Restarting has no effect.
[pullover.1.log](https://github.com/cgrossde/Pullover/files/1948235/pullover.1.log)

**Comment by cgrossde** [comment]
Please try the new version, it should be fixed there: [1.3.0](https://github.com/cgrossde/Pullover/releases/tag/1.3.0)
If not please reopen this issue.
