### ISSUE TITLE
Notification placement

### ISSUE THREAD

**Issue by meat-ball** [cgrossde/Pullover#15]
Hi, is is possible down the road to add the notification placement option for Pullover? Currently I get them in the lower right corner. Ideally (for me) they would go in the upper right- where my other notifications are placed.  Just an idea.

Thanks

**Comment by cgrossde** [comment]
Of course it would be possible, PRs welcome ;) 
Which system are you using? If you use Mac then you can disable the new notification system and use OS X's native system which is in the upper right corner.

**Comment by meat-ball** [comment]
actually I’ll do that (pull request).

sorry I didnt realize it would default to os x notifications (upper right).

that said, I like the pullover notifications. Ill see what I can do to keep them but have a location option (doable in growl but rather not run both)


—
Damien

**Comment by cgrossde** [comment]
I outsourced the notification feature in the [nw-notify](https://github.com/cgrossde/nw-notify) package. Take a look at the `index.js* starting at about [line 137|(https://github.com/cgrossde/nw-notify/blob/master/index.js#L137).

**Comment by meat-ball** [comment]
great, I’ll take a peak at it today. Thanks!


—
Damien
