### ISSUE TITLE
Play sound upon notification

### ISSUE THREAD

**Issue by theradiodude** [cgrossde/Pullover#16]
I would like to see this client have an option to make some sort of sound upon notification in addition to the pop up.

**Comment by cgrossde** [comment]
If you are using Mac OS X then disable the *Use new notifications* option. After that Pullover will use the native mac notification center. In the notification center settings you can specify if you want to play a sound.

Bad news (for now) if you use Windows, no option to play sounds. But I will try to add this feature with the next release.

**Comment by XGhozt00** [comment]
Any hope in using the native windows 10 notification center?

**Comment by cgrossde** [comment]
I will have a look at it, don't know if node-webkit already has support for this.

**Comment by cgrossde** [comment]
Please try the new alpha, it's a complete rewrite: 
https://github.com/cgrossde/Pullover/releases/tag/1.0.0-alpha.1
