### ISSUE TITLE
Multiple Menu Bar Instances

### ISSUE THREAD

**Issue by RobertAlan** [cgrossde/Pullover#18]
![screenshot_2_24_15__1_32_pm](https://cloud.githubusercontent.com/assets/5241923/6357377/a4cdbfde-bc29-11e4-98b1-2d107c8c6c81.png)

**Comment by cgrossde** [comment]
Could you post the log files in `/Users/user/Library/Application Support/pullover` on pastebin or in a gist?
Pullover shouldn't start more than once, even if you try to. Please also have a look at your *System Preferences > Users & Groups* and check if Pullover appears multiple times under *Login objects*.
![bildschirmfoto 2015-02-25 um 09 48 57](https://cloud.githubusercontent.com/assets/2333584/6367444/8d59f93a-bcd3-11e4-9f92-62e880ce2a7d.png)

**Comment by RobertAlan** [comment]
Chris,

Really sorry for the delayed response here. The issue seems to have worked itself out but I’m attaching the log as well.

http://pastebin.com/28et86h8
http://pastebin.com/dE6USdwP
http://pastebin.com/XEDSM9YC
http://pastebin.com/3JK4eDYS

There are no duplicates in ‘Login objects’

Love Pullover!

Kindest Regards,
Robert

From: Chris
Reply-To: cgrossde/Pullover
Date: Wednesday, February 25, 2015 at 2:49 AM
To: cgrossde/Pullover
Cc: Robert Anderson
Subject: Re: [Pullover] Multiple Menu Bar Instances (#18)


Could you post the log files in /Users/user/Library/Application Support/pullover on pastebin or in a gist?
Pullover shouldn't start more than once, even if you try to. Please also have a look at your System Preferences > Users & Groups and check if Pullover appears multiple times under Login objects.
[bildschirmfoto 2015-02-25 um 09 48 57]<https://cloud.githubusercontent.com/assets/2333584/6367444/8d59f93a-bcd3-11e4-9f92-62e880ce2a7d.png>

**Comment by cgrossde** [comment]
Okay, thanks for the reply. I will close it for now, feel free to reopen it if it occurs again.
