### ISSUE TITLE
auto reconnect

### ISSUE THREAD

**Issue by mason105** [cgrossde/Pullover#19]
hi,
 can u add this function? 
 when disconnect,it can auto reconnect each 5 or 10 seconds?

**Comment by cgrossde** [comment]
It should do that, but I think somethings broke. I will have some time for Pullover again in April. Will have a look at it then.

**Comment by cgrossde** [comment]
Will close it for now, since I'm rewriting/restructuring Pullover for the next release. Feel free to reopen it if this bug is still present in future releases (> 0.3.1).

**Comment by rastarr** [comment]
both my friend and I are running 0.3.2 and this persistent failure to reconnect is still evident unfortunately
Manually clicking Reconnect causes the app to produce a recurring Login Failed message
We both need to Logout and Login again and create a new device so it is most frustrating

Any chance of a fix please?
