### ISSUE TITLE
No sound on notifications on Mac?

### ISSUE THREAD

**Issue by buddy-texas** [cgrossde/Pullover#20]
Just installed 0.3.1 DMG for my OSX 10.9.5.  I'm trying to send a message, which delivers correctly, but with no sound.  I'm using Zapier Webhook to do a POST and it found all the necessary Properties, but sound doesn't seem to be working.

**Comment by cgrossde** [comment]
This seems to be a duplicate of #16. Disable "Use new notification system" and open your Mac Notification Center settings. There you can define if the MNC will play a sound upon new notifications from Pullover.
