### ISSUE TITLE
Respect Priority & Only Show last X messages

### ISSUE THREAD

**Issue by brettyj** [cgrossde/Pullover#21]
Hey

Loving the app, the only things I'd like are:

* Respect priority, so if the priority is -2 - it doesn't appear (I use -2 for Infomation Logging that I like to be able to easily see, but I don't need to be pushed to me), likewise if a notification is +2, would be good to see the notification appear red or something.

* Only show last X messages. I had the app closed for a couple of days, when I re-opened it, every single message that it had missed came up one after the other, all of these I had already seen on my other devices, so it would be good if there was some way of stopping this flood.

Thanks!

**Comment by cgrossde** [comment]
Hey, thanks for the good feedback. I'm currently working again on Pullover and rewriting/restructuring it. This is definitely on my list.

**Comment by cgrossde** [comment]
Partially fixed in rewrite (limit shown notifications at once): 
https://github.com/cgrossde/Pullover/releases/tag/1.0.0-alpha.1

**Comment by cgrossde** [comment]
Resolved (priority and limit) in [1.0.0-beta.1](https://github.com/cgrossde/Pullover/releases/tag/1.0.0-beta.1)
