### ISSUE TITLE
React to new "E" frame and send User-Agent

### ISSUE THREAD

**Issue by jcs** [cgrossde/Pullover#22]
The Open Client API [documentation](https://pushover.net/api/client#websocket) has been updated today to reflect a new "E" frame that is sent upon a login failure, before closing the connection.  Pullover should react to this frame by considering it a permanent failure, which should stop its reconnection retry loop and raise an error to the user.  This login failure can happen if the user's device is disabled (for licensing or otherwise) or the secret is invalid.

Also, if you could [send a User-Agent string](https://pushover.net/api/client#friendly) of something containing Pullover so it can be identified in our logs, that would help diagnose problems.  Thanks!

**Comment by cgrossde** [comment]
Good to know, will implement this today or within the next days. Thanks for adding the "E" frame, it will simplify my code and make things more reliable :)

**Comment by cgrossde** [comment]
Fixed with [latest release](https://github.com/cgrossde/Pullover/releases/v0.3.2)
