### ISSUE TITLE
libnotify.so.4 not found

### ISSUE THREAD

**Issue by chrishar** [cgrossde/Pullover#24]
When starting on Linux Mint the following error occurred:

./pullover: error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory

**Comment by cgrossde** [comment]
I'm sorry but I do not give support for Linux since I don't use is as a desktop system. Please use google ("nodewebkit lib notify.so.4 ..") and checkout shama/nodewebkit#48. Maybe you can solve this yourself ;)

**Comment by chrishar** [comment]
After following the steps and creating a symlink, it still does not work on 64bit:
```
./pullover: error while loading shared libraries: libnotify.so.4: wrong ELF class: ELFCLASS64
```

**Comment by cgrossde** [comment]
Try the 32 bit version, Pullover for linux is also 32 bit.

**Comment by chrishar** [comment]
### Finally it worked.
Installing the ia32-libs as well as creating symlinks inside of /usr/lib/ did not solve the problem. Better download the 32 bit version of libnotify.so.4 or libnotify.so.4.0.0 and add it to the library path. The libnotify.so.4.0.0 must be renamed to libnotify.so.4

Starting pullover with additional library path:
```
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/path/to/folder/containing/libnotify.so.4/" ./pullover
```
Further thoughts:
Make sure you have created and chowned /var/local/Pullover. Logs of pullover are placed here. After authentication the configuration is placed inside ~/.config/pullover/

@cgrossde maybe you should place a hint for users of 64 bit linux distributions

**Comment by cgrossde** [comment]
@chrishar Thank you very much for you efforts, I created a wiki page (https://github.com/cgrossde/Pullover/wiki/Installing-on-Linux) with your instructions, feel free to edit it should the installation process change. Maybe you even have an init.d / upstart / ... script ? ;)
