### ISSUE TITLE
0.3.2 not seeing tray notifications windows 7

### ISSUE THREAD

**Issue by genepool99** [cgrossde/Pullover#25]
Using Windows 7-64, notifications do not come to the top focus and are displayed behind the open applications.

![push issue](https://cloud.githubusercontent.com/assets/3596229/7887715/f14fdbd2-05e7-11e5-9acb-cf8ff273cc54.png)

**Comment by cgrossde** [comment]
Anyone else experiencing this behavior?

**Comment by Terrovan** [comment]
Experiencing the same issues. Windows 7-64bit. 

Mon Jun 15 2015 13:54:06 GMT+1000 (AUS Eastern Standard Time)  App      'Conn-status:'   1
Mon Jun 15 2015 13:54:06 GMT+1000 (AUS Eastern Standard Time)  OpenClient      'OpenClient.prototype.lastInteractionDate'
Mon Jun 15 2015 13:54:06 GMT+1000 (AUS Eastern Standard Time)  OpenClient      'OpenClient.prototype.lastInteractionDate'
Mon Jun 15 2015 13:54:34 GMT+1000 (AUS Eastern Standard Time)  OpenClient      'OpenClient.prototype._parseCommand'
Mon Jun 15 2015 13:54:34 GMT+1000 (AUS Eastern Standard Time)  OpenClient      'OpenClient.prototype._resetKeepAlive'
Mon Jun 15 2015 13:54:34 GMT+1000 (AUS Eastern Standard Time)  App      'Conn-status:'   1
Mon Jun 15 2015 13:54:34 GMT+1000 (AUS Eastern Standard Time)  OpenClient      'OpenClient.prototype.lastInteractionDate'
Mon Jun 15 2015 13:54:34 GMT+1000 (AUS Eastern Standard Time)  OpenClient      'OpenClient.prototype.lastInteractionDate'
Mon Jun 15 2015 13:54:34 GMT+1000 (AUS Eastern Standard Time)  OpenClient      'OpenClient.prototype._stopKeepAlive'
Mon Jun 15 2015 13:54:56 GMT+1000 (AUS Eastern Standard Time)  OpenClient      'OpenClient.prototype._parseCommand'
Mon Jun 15 2015 13:54:56 GMT+1000 (AUS Eastern Standard Time)  OpenClient      'OpenClient.prototype._resetKeepAlive'
Mon Jun 15 2015 13:54:56 GMT+1000 (AUS Eastern Standard Time)  App      'Conn-status:'   1
Mon Jun 15 2015 13:54:56 GMT+1000 (AUS Eastern Standard Time)  OpenClient      'OpenClient.prototype.lastInteractionDate'
Mon Jun 15 2015 13:54:56 GMT+1000 (AUS Eastern Standard Time)  OpenClient      'OpenClient.prototype.lastInteractionDate'
Mon Jun 15 2015 13:54:56 GMT+1000 (AUS Eastern Standard Time)  OpenClient      'OpenClient.prototype._stopKeepAlive'
Mon Jun 15 2015 13:54:56 GMT+1000 (AUS Eastern Standard Time)  App      'getMessages - try request'
Mon Jun 15 2015 13:54:56 GMT+1000 (AUS Eastern Standard Time)  OpenClient      'OpenClient.prototype.fetchNotifications'
Mon Jun 15 2015 13:54:57 GMT+1000 (AUS Eastern Standard Time)  App      'getMessages - successful'
Mon Jun 15 2015 13:54:57 GMT+1000 (AUS Eastern Standard Time)  App      'New messages: 1'
Mon Jun 15 2015 13:54:57 GMT+1000 (AUS Eastern Standard Time)  OpenClient      'OpenClient.prototype.acknowledgeNotification'
Mon Jun 15 2015 13:55:04 GMT+1000 (AUS Eastern Standard Time)  OpenClient      'OpenClient.prototype._parseCommand'
Mon Jun 15 2015 13:55:04 GMT+1000 (AUS Eastern Standard Time)  OpenClient      'OpenClient.prototype._resetKeepAlive'
Mon Jun 15 2015 13:55:04 GMT+1000 (AUS Eastern Standard Time)  App      'Conn-status:'   1
Mon Jun 15 2015 13:55:04 GMT+1000 (AUS Eastern Standard Time)  OpenClient      'OpenClient.prototype.lastInteractionDate'
Mon Jun 15 2015 13:55:04 GMT+1000 (AUS Eastern Standard Time)  OpenClient      'OpenClient.prototype.lastInteractionDate'
Mon Jun 15 2015 13:55:04 GMT+1000 (AUS Eastern Standard Time)  OpenClient      'OpenClient.prototype._stopKeepAlive'

Seems to be receiving the notification, just not displaying it.

**Comment by Terrovan** [comment]
It has just started working this morning. Last Synced 1 hour, according to Pushover dashboard. Pullover was logged out, Had to login and create the Device name again, and now messages are coming through. 

Must have been an issue with Pushover?

**Comment by AllanMar** [comment]
I'm having this issue. Win7 not displaying notifications. I've tried restarting/re-registering with no 
change.
Tue Aug 18 2015 19:03:59 GMT-0300 (Atlantic Daylight Time)  OpenClient      'OpenClient.prototype._parseCommand'
Tue Aug 18 2015 19:03:59 GMT-0300 (Atlantic Daylight Time)  OpenClient      'OpenClient.prototype._resetKeepAlive'
Tue Aug 18 2015 19:03:59 GMT-0300 (Atlantic Daylight Time)  App      'Conn-status:'   1
Tue Aug 18 2015 19:03:59 GMT-0300 (Atlantic Daylight Time)  OpenClient      'OpenClient.prototype.lastInteractionDate'
Tue Aug 18 2015 19:03:59 GMT-0300 (Atlantic Daylight Time)  OpenClient      'OpenClient.prototype.lastInteractionDate'
Tue Aug 18 2015 19:03:59 GMT-0300 (Atlantic Daylight Time)  OpenClient      'OpenClient.prototype._stopKeepAlive'
Tue Aug 18 2015 19:03:59 GMT-0300 (Atlantic Daylight Time)  App      'getMessages - try request'
Tue Aug 18 2015 19:03:59 GMT-0300 (Atlantic Daylight Time)  OpenClient      'OpenClient.prototype.fetchNotifications'
Tue Aug 18 2015 19:04:00 GMT-0300 (Atlantic Daylight Time)  App      'getMessages - successful'
Tue Aug 18 2015 19:04:00 GMT-0300 (Atlantic Daylight Time)  App      'New messages: 1'
Tue Aug 18 2015 19:04:00 GMT-0300 (Atlantic Daylight Time)  OpenClient      'OpenClient.prototype.acknowledgeNotification'
Tue Aug 18 2015 19:04:05 GMT-0300 (Atlantic Daylight Time)  App      'Conn-status:'   1
Tue Aug 18 2015 19:04:05 GMT-0300 (Atlantic Daylight Time)  OpenClient      'OpenClient.prototype.lastInteractionDate'
Tue Aug 18 2015 19:04:05 GMT-0300 (Atlantic Daylight Time)  OpenClient      'OpenClient.prototype.lastInteractionDate'
Tue Aug 18 2015 19:04:24 GMT-0300 (Atlantic Daylight Time)  OpenClient      'OpenClient.prototype._parseCommand'
Tue Aug 18 2015 19:04:24 GMT-0300 (Atlantic Daylight Time)  OpenClient      'OpenClient.prototype._resetKeepAlive'
Tue Aug 18 2015 19:04:24 GMT-0300 (Atlantic Daylight Time)  App      'Conn-status:'   1

**Comment by cgrossde** [comment]
Please try the new alpha, it's a complete rewrite: 
https://github.com/cgrossde/Pullover/releases/tag/1.0.0-alpha.1
