### ISSUE TITLE
Auto Reconnect

### ISSUE THREAD

**Issue by rastarr** [cgrossde/Pullover#26]
This is a continuation of https://github.com/cgrossde/Pullover/issues/19
Sorry, I was't able to re-open that issue

both my friend and I are running 0.3.2 and this persistent failure to reconnect is still evident unfortunately
Manually clicking Reconnect causes the app to produce a recurring Login Failed message
We both need to Logout and Login again and create a new device so it is most frustrating

Any chance of a fix please?

**Comment by cgrossde** [comment]
Can you please post the contents of the log file around the time it happened. Sometimes the API from Pushover rejects a login (don't know why) but in my case it worked after a reconnect.

**Comment by cgrossde** [comment]
Duplicate of #29
