### ISSUE TITLE
Mac: Non Retina menubar icon

### ISSUE THREAD

**Issue by iAmRenzo** [cgrossde/Pullover#27]
It seems that all the images in the app (for Mac) are retina except the menubar icons.
![screen shot 2015-06-27 at 15 26 04](https://cloud.githubusercontent.com/assets/1183790/8392166/de5d9d9c-1ce0-11e5-9a49-65ebefe7dbc6.png)

**Comment by cgrossde** [comment]
Will be fixed in the rewrite which I started a few days ago.
