### ISSUE TITLE
Support for Acknowledging Notifications

### ISSUE THREAD

**Issue by ggiesen** [cgrossde/Pullover#28]
Would it be possible to get support for acknowledging notifications? The Android client at least (and I suspect all the official clients) support acknowledging notifications, which allows Pushover to call a callback URL when the notification is acknowledged (this can also be polled). .

If you set a page to be emergency priority (2), and you set a retry and expire parameters, Pushover will send the message over and over (every retry interval) until it's acknowledged or the expire time is reached.

Would be great if Pullover supported being able to acknowledge these types of notifications (we're planning to roll out Pushover/Pullover as an internal paging service).

**Comment by cgrossde** [comment]
Possible of course but due to my very limited time at the moment I don't see it happen soon. Feel free to contribute to this Repository. I plan on rewriting Pullover sometime in the future and will add this to the feature list.

**Comment by XGhozt00** [comment]
I second this! This is a great script, but sometimes I have notifications that require acknowledgement and they start to add up. After 15 of them or so it's just a constant stream of repeating notifications which makes Pullover kind of useless. The only way I've been able to make it stop is to wait for them to expired or to delete the pullover cache.

**Comment by cgrossde** [comment]
I would have to adapt nw-notify to support buttons and I don't have the time currently. But I will rewrite Pullover eventually and this feature is on my list.

**Comment by XGhozt00** [comment]
What about a patch in the mean time to automatically acknowledge the notifications? Then they just show once and they're just acknowledged for pullover. We would really appreciate it!

**Comment by ggiesen** [comment]
I wouldn't be in favour of that, unless it was configurable (ie a checkbox for "Automatically acknowledge all notifications"). We Pushover/Pullover as an IT paging system, and to us an acknowledgement means an engineer has received the page and is actively working on the problem. Automatically acknowledging all notifications would break that.

**Comment by XGhozt00** [comment]
@ggiesen; I think a checkbox is a great idea. This is just a simple solution, I suspect we can just add a single query string to the API call to send the acknowledgement so it's always on. I think you can configure Pushover to not sync the acknowledgement that to other devices on the account. So this way it will keep reminding you on, say, your phone, but not on Pullover.

**Comment by danbob123** [comment]
+1

**Comment by cgrossde** [comment]
Added to feature wish list: #85

**Comment by dilowach** [comment]
are there some news regarding 'acknowledge notification' in Pullover ?
