### ISSUE TITLE
disconnection is bad

### ISSUE THREAD

**Issue by boneskull** [cgrossde/Pullover#29]
If I have Pullover running, and for some reason I lose my internet connection, it is bad.  What happens is:

- Pullover notifies me I am disconnected, and prompts me to reconnect
- I attempt to reconnect
- Pushover informs me the API denied my login request, and I have to login again
- So I login again with my username and password
- I am forced to create a new device
- I can't use the same device name, so now I have several dupes in my Pushover account

**Comment by boneskull** [comment]
oh, and after I do this, there are two P's in my menu bar.

**Comment by cgrossde** [comment]
What OS do you have? I know that sometimes Pullover claims the login data is invalid. Just ignore it, and try to reconnect. Maybe wait some time before you reconnect but usually it should work again without login in again. Could you also post your log-files around the time this happened? (Under settings is a link to open the log file folder. Just send mit pullover.1.log via mail or copy and paste the most recent lines around the time your login was denied.

**Comment by sejmann** [comment]
This has been happening to me, as well, on my mac.  It refuses to reconnect, even after a delay.

**Comment by boneskull** [comment]
@sejmann it appears sometimes if I wait long enough, reconnection will work correctly.

@cgrossde MacOS X El Capitan.  Let me reproduce and send a log

**Comment by boneskull** [comment]
@cgrossde ugh, I can't reproduce.  I'll just send it next time it happens.

**Comment by sejmann** [comment]
El Capitan here, too.  I looked through the log, replacing normal/error free 30 second blocks (from _parseCommand to _stopKeepAlive) with a single period, so only interesting stuff should remain.

http://pastebin.com/LGF3W6Nm

I guess it frequently did recover by retrying, and I only noticed the error when I happened to be at the computer when it happened.  Several times the error seemed to be preceeded by TIMEOUTs.

**Comment by cgrossde** [comment]
I'm currently rewriting Pullover and aware of the problem (the web socket does not know when the internet gets disconnected, also it does not recovery nicely after waking from sleep and sometimes the API endpoint sends an error code that the current login is invalid - not true ...). The new Pullover will have a more robust connection handling. 

I don't want to spend time on fixing the soon to be abandoned (dirty) code, so please be patient with me and I will release the rewrite as soon as possible ;)

**Comment by cgrossde** [comment]
Please try the new alpha, it's a complete rewrite: 
https://github.com/cgrossde/Pullover/releases/tag/1.0.0-alpha.1
