### ISSUE TITLE
Build 64  bit version

### ISSUE THREAD

**Issue by alitvak69** [cgrossde/Pullover#31]
I wonder if there is a way to build a linux 64 bit version.  I really want to avoid loading all the libraries below.  Is building code on MAC is the only option?

ldd pullover 
        linux-gate.so.1 (0xf76f5000)
        librt.so.1 => /lib/librt.so.1 (0xf76b6000)
        libdl.so.2 => /lib/libdl.so.2 (0xf76b1000)
        libm.so.6 => /lib/libm.so.6 (0xf766b000)
        libgobject-2.0.so.0 => not found
        libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0xf7557000)
        libnss3.so => not found
        libnssutil3.so => not found
        libsmime3.so => not found
        libplc4.so => not found
        libnspr4.so => not found
        libgconf-2.so.4 => not found
        libgio-2.0.so.0 => not found
        libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0xf7519000)
        libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0xf7487000)                                                                                           
        libpangocairo-1.0.so.0 => not found                                                                                                                  
        libcairo.so.2 => not found                                                                                                                           
        libpango-1.0.so.0 => not found                                                                                                                       
        libX11.so.6 => /usr/lib/libX11.so.6 (0xf734b000)                                                                                                     
        libXi.so.6 => not found
        libXcursor.so.1 => not found
        libXext.so.6 => /usr/lib/libXext.so.6 (0xf7337000)
        libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0xf7331000)
        libXrender.so.1 => /usr/lib/libXrender.so.1 (0xf7326000)
        libXcomposite.so.1 => not found
        libasound.so.2 => /usr/lib/libasound.so.2 (0xf723b000)
        libXdamage.so.1 => /usr/lib/libXdamage.so.1 (0xf7237000)
        libXtst.so.6 => /usr/lib/libXtst.so.6 (0xf7230000)
        libXrandr.so.2 => /usr/lib/libXrandr.so.2 (0xf7225000)
        libexpat.so.1 => /usr/lib/libexpat.so.1 (0xf71fc000)
        libdbus-1.so.3 => /lib/libdbus-1.so.3 (0xf71af000)
        libpthread.so.0 => /lib/libpthread.so.0 (0xf7193000)
        libgtk-x11-2.0.so.0 => not found
        libgdk-x11-2.0.so.0 => not found
        libgdk_pixbuf-2.0.so.0 => not found
        libnotify.so.4 => not found
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0xf70a5000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0xf7088000)
        libc.so.6 => /lib/libc.so.6 (0xf6edb000)
        /lib/ld-linux.so.2 (0xf76f8000)
        libpcre.so.1 => /usr/lib/libpcre.so.1 (0xf6e6a000)
        libz.so.1 => /lib/libz.so.1 (0xf6e53000)
        libpng16.so.16 => /usr/lib/libpng16.so.16 (0xf6e16000)
        libxcb.so.1 => /usr/lib/libxcb.so.1 (0xf6df3000)
        libXau.so.6 => /usr/lib/libXau.so.6 (0xf6def000)

**Comment by cgrossde** [comment]
I rebuild a x64 version for you. You can find it on the [current release page](https://github.com/cgrossde/Pullover/releases/tag/v0.3.2). I will provide x64 releases in the future, didn't know anyone uses them.

**Comment by alitvak69** [comment]
Thank you very much for your support.
