### ISSUE TITLE
Use different log path for Linux

### ISSUE THREAD

**Issue by slokhorst** [cgrossde/Pullover#32]
Currently, as described in "Installing on Linux", we need to own the `/var/local/Pulldown` directory. This can obviously lead to problems, for instance when having multiple users using Pulldown. Also, I can't see why one would run Pulldown as a system daemon.

Can you please change `appDataPath` on Linux to something like `process.env.HOME + '/.local/share'`? So that the log path will become `~/.local/share/Pulldown`?

Thanks for creating this awesome program!

**Comment by cgrossde** [comment]
You are totally right, I don't use linux (anymore). This will definitely change with the next version of Pullover.

**Comment by cgrossde** [comment]
Note to self: Take a look at [ XDG_DATA_HOME environment variable](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables)

**Comment by cgrossde** [comment]
Fixed in new alpha. Will try to use `$XDG_DATA_HOME/Pullover` and fallback to `$HOME/.local/share/Pullover`
Please try it out and report bugs:
https://github.com/cgrossde/Pullover/releases/tag/1.0.0-alpha.1

**Comment by cgrossde** [comment]
Also if you know how to put Pullover into a nice .deb any help would be appreciated ;)
See issue #13

**Comment by lonaowna** [comment]
The new alpha looks good! But there's a crucial typo:

`process.env.HOME + './local/share'` should be `process.env.HOME + '/.local/share'` (the dot should be *after* the first slash).

I'm afraid I can't help with a .deb... I use Arch Linux myself and am not familiar with Debian at all. Maybe if I have some time I can look at it.

**Comment by cgrossde** [comment]
Thanks for finding this :) Will be fixed with the next alpha/beta.

**Comment by cgrossde** [comment]
Fixed in [1.0.0-beta.1](https://github.com/cgrossde/Pullover/releases/tag/1.0.0-beta.1)
