### ISSUE TITLE
notifications position

### ISSUE THREAD

**Issue by t3t3** [cgrossde/Pullover#34]
.... seems to be fixed to the bottom right corner of the screen - just not everyone has the task bar on the bottom of the screen ;) where this would also match the taskbar icon position; so either adjusting it to the actual taskbar / taskbar icon position, or even to allow choosing a corner would be nice.

**Comment by cgrossde** [comment]
This is a limitation of the used notification library: `nw-notify`. It can only display notifications in the bottom right corner. I'm sorry but I don't have time to implement this.
