### ISSUE TITLE
Windows package in ZIP file

### ISSUE THREAD

**Issue by struthio** [cgrossde/Pullover#35]
Please provide pullover application in ZIP file, so no installation is requires (only unpacking).
Some kind of 'Portable' version.

**Comment by cgrossde** [comment]
I could provide a ZIP file but that would not make it portable because it stores the Settings locally `C:\Users\User\AppData\Roaming\Pullover`

**Comment by struthio** [comment]
If settings are stored on local drive, then there is no point in ZIP file.
Thanks for answer.
