### ISSUE TITLE
Mac menubar icon isn't retina and is heavily black

### ISSUE THREAD

**Issue by iAmRenzo** [cgrossde/Pullover#38]
The menubar icon on Mac is heavily black and still non retina.

**Comment by cgrossde** [comment]
Will be fixed in next release.

**Comment by iAmRenzo** [comment]
Is there a ETA for the next release?

**Comment by cgrossde** [comment]
Not really. The rewrite is almost but there are still some lose ends. You can check it out in the `develop` branch.

**Comment by cgrossde** [comment]
Fixed in the new alpha, please try:
https://github.com/cgrossde/Pullover/releases/tag/1.0.0-alpha.1
