### ISSUE TITLE
Notifications showing up on wrong display

### ISSUE THREAD

**Issue by X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-XX** [cgrossde/Pullover#39]
The pushover notifications are set to show up on monitor 1 and I'd rather have them show up on monitor 2 or 3. Please implement an option for this

**Comment by cgrossde** [comment]
This is currently not supported by the notification library `nw-notify`. Feel free to implement the feature and post a PR there: https://github.com/cgrossde/nw-notify
