### ISSUE TITLE
Cannot get past "Register this device"

### ISSUE THREAD

**Issue by eriknomitch** [cgrossde/Pullover#40]
Title says it all.  It just loops back to that menu screen indefinitely.

It's been working before on this machine and suddenly stopped.  I reinstalled and logged out - same issue.  v.0.3.2

Erik

**Comment by cgrossde** [comment]
Do you still experience this issue?

**Comment by eriknomitch** [comment]
I am. I'm using v.0.3.2 from Homebrew Cask.

**Comment by cgrossde** [comment]
Please try the new alpha, it's a complete rewrite: 
https://github.com/cgrossde/Pullover/releases/tag/1.0.0-alpha.1

**Comment by eriknomitch** [comment]
@cgrossde That fixed it.  Thank you!
