### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by caiogui** [cgrossde/Pullover#41]
[pullover.2.zip](https://github.com/cgrossde/Pullover/files/144530/pullover.2.zip)

**Comment by cgrossde** [comment]
Please don't upload zips only log files and also give a short description what happened before the error.

**Comment by caiogui** [comment]
Hi There

i just followed instructions on the screen. i don't know what happened..it
was apparently working.. icon in the tray. i went away to sleep when i got
back the message fatal error was on the screen instructing me to send the
log.. the log was 30MB.. it didn't make sense for me to send a 30mb file
when i can compress to help both ways.. since most email systems don't
receive more than 20mb sized email i will repeat this operation on the
github with uncompressed log

2016-02-24 11:36 GMT-03:00 Chris <notifications@github.com>:

**Comment by cgrossde** [comment]
You can just post the last few lines of the log, no need for the full log

**Comment by cgrossde** [comment]
Please try the new alpha, it's a complete rewrite: 
https://github.com/cgrossde/Pullover/releases/tag/1.0.0-alpha.1
