### ISSUE TITLE
alpha: status "STOPPED" when first logged in.  Had to restart before went "ONLINE"

### ISSUE THREAD

**Issue by sejmann** [cgrossde/Pullover#42]
Hey, so far so good with the rewritten alpha; haven't suffered random disconnects.  But initially after logging in, the status remained "STOPPED" and I couldn't figure out how to start it.  I restarted the app, and then it showed as being "ONLINE".  (However, it lost my "Run on Startup" and "Use Native Notifications" settings, so I had to reset them.)  It's been fine ever since.

**Comment by cgrossde** [comment]
Damn, forgot to check for naming conflicts with the old version in localStorage. Will write some upgrade logic to keep the other settings. Thanks for the info.

**Comment by cgrossde** [comment]
Fixed in [1.0.0-beta.1](https://github.com/cgrossde/Pullover/releases/tag/1.0.0-beta.1)
