### ISSUE TITLE
Properly show HTML or strip it for OSX notifications

### ISSUE THREAD

**Issue by jens-maus** [cgrossde/Pullover#45]
I have just noticed that when sending HTML-based notifications around pushover the Pullover client only supports HTML in its own notification window. As soon as I switch to native OSX notifications the HTML code is shown instead of interpreting the HTML tags accordingly. 

While this might be perfectly a limitation of the OSX notification engine (is this really true?) it would be great to at least change Pullover that it automatically strips any HTML tags as soon as the OSX notifications are used. Best would be, however, to actually interpret the HTML tags and let OSX notifications also interpret the HTML stuff.

BTW: I am using your latest 1.0.0-alpha version and it works fine so far.

**Comment by cgrossde** [comment]
Thanks for the report. This is a limitation of native notifications, OS X can't handle HTML in notifications. I will strip the tags for native notifications. Will be fixed in next alpha/beta.

**Comment by cgrossde** [comment]
Fixed in [1.0.0-beta.1](https://github.com/cgrossde/Pullover/releases/tag/1.0.0-beta.1)
