### ISSUE TITLE
notifications without subject/title show truncated in OSX notification center

### ISSUE THREAD

**Issue by jens-maus** [cgrossde/Pullover#48]
When using OSX native notification setting in Pullover message appear somewhat truncated if they do not contain any subject/title information. Please see the following screenshot of the OSX notification center:

![screenshot_73](https://cloud.githubusercontent.com/assets/5887769/14345450/22407adc-fcad-11e5-9e47-b46669584d41.png)

Here you can see that while the first message was sent with a subject/title "TEST1" the second message has an empty subject/title and will be somewhat shown truncated so that the "Vor X Min." is not visible anymore.

Here I am using the latest Pullover 1.0.0-beta.1 on OSX 10.11.4 El Capitan

**Comment by cgrossde** [comment]
I have no influence on the native notification center in OS X but the new release should fix this by adding the app name as title if none was provided: Please try the new version: [1.0.0-beta.2](https://github.com/cgrossde/Pullover/releases/tag/1.0.0-beta.2)
