### ISSUE TITLE
Subject/Title omitted in Pullover while official iOS App shows Application Name

### ISSUE THREAD

**Issue by jens-maus** [cgrossde/Pullover#49]
Somewhat related to #48 I noticed that the official iOS Pushover App displays the user choosen application name or "Pushover" (for default messages) for notifications where no title/subject has been added. Pullover however omits the title/subject completly which actually triggers the problem seen in #48.

Here the output from the native iOS Pushover App:
![img_6363](https://cloud.githubusercontent.com/assets/5887769/14345749/0ecce6aa-fcaf-11e5-8090-18f321679e39.jpg)

Here the output from Pullover:
![screenshot_76](https://cloud.githubusercontent.com/assets/5887769/14345766/2648da14-fcaf-11e5-93cc-d18e46db0dd5.png)

Please note that the official iOS Pushover App is adding an own subject/title based on the Application Name if there is no explicit subject/title added when submitting the message.

I am using Pullover 1.0.0-beta.1 here on OSX 10.11.4 El Capitan

**Comment by cgrossde** [comment]
Fixed in the new version, if no title was provided the app name is used: [1.0.0-beta.2](https://github.com/cgrossde/Pullover/releases/tag/1.0.0-beta.2)
