### ISSUE TITLE
Ignore old notifications.

### ISSUE THREAD

**Issue by filicivi** [cgrossde/Pullover#51]
It's possibile to ignore old notifications not showed by Pullover?
After a long time no run, I'm receiveing a lot of notification and I can't stop it.

**Comment by cgrossde** [comment]
Try the [beta version of Pullover 1.0.0](https://github.com/cgrossde/Pullover/releases) and use the "Max. notification queue" feature
![maxNotificationQueue](https://cloud.githubusercontent.com/assets/2333584/13635607/36770bf4-e5fd-11e5-8f1b-dfc69297e044.png)
If there are more notifications due than specified by this setting, only the latest X are presented, the rest is not shown.
