### ISSUE TITLE
On WIndows7 64bit no Push Notification

### ISSUE THREAD

**Issue by markus2701** [cgrossde/Pullover#56]
I can not see any Push Notification. No PopUp Window.

**Comment by cgrossde** [comment]
Anyone else experiencing this issue?

Make sure "Native notifications" is not checked.
![bildschirmfoto 2016-06-11 um 13 24 26](https://cloud.githubusercontent.com/assets/2333584/15984794/da38a580-2fd7-11e6-8372-53a3113565a7.png)

**Comment by cgrossde** [comment]
Closing this, please reopen if you have this issue.
