### ISSUE TITLE
[feature request] Either a customizable css sheet option or at least a dark version

### ISSUE THREAD

**Issue by SpaceOctopus** [cgrossde/Pullover#57]
Hi. Thanks for developing this! :heart_eyes_cat: 
<sup>I was pretty irritated when I found Pushover & thought I might be able to use it but found I couldn't since there was no desktop version. They stupidly think "web version" means the same thing as "desktop version". Anyone with a brain knows this is not the same thing. Then I saw you made this, and I was very happy.</sup>

I just wanted to request a way to easily change the appearance. I personally _**loathe**_ white being the basis for anything on my screen, and try to minimize it where I can (it's also an eye strainer). It would also just be a really cool feature. I saw that this can be compiled on a mac, but didn't see a mention about Windows. 
Is there already a file I can mess with to change the appearance on my own? I have a couple tools that can open just about anything & I'm sure I could figure it out if you point me to the right file or whatever. Even if I'm unfamiliar with the language, I am great at messing with things to get them to do what I want/need. :P

**Comment by cgrossde** [comment]
Thanks for your feedback, but I don't have the time currently to implement this. But you can compile Windows versions on Windows, just follow the instruction in the README: https://github.com/cgrossde/Pullover#build-your-own

You can find the SASS files under `/src/app/styles/` and `/src/app/components/`. You need to run `webpack` after changing those files. Use `./builder` to bundle your adapted Version into an installer.
