### ISSUE TITLE
OSX - Disable or Replace Pullover icon...

### ISSUE THREAD

**Issue by TheReiner** [cgrossde/Pullover#60]
I have 2 icons in my notification, in left "Pullover" and in right "MyIcon", that's possible to disable ?Pullover Icon when we have a own icon ? Thanks

**Comment by cgrossde** [comment]
Don't understand what you mean. First of all which OS are you using?

**Comment by TheReiner** [comment]
OS X and Look my screen shot …. Thanks

**Comment by cgrossde** [comment]
Please upload the screenshot using your browser (https://github.com/cgrossde/Pullover/issues/60#issuecomment-232640356), I can't see email attachments on Github :(

**Comment by TheReiner** [comment]
![screen shot 2016-07-14 at 13 51 42](https://cloud.githubusercontent.com/assets/18024918/16838589/2e8f394e-49ca-11e6-9a8d-11622136b633.png)

**Comment by cgrossde** [comment]
Now I understand. The left icon is the icon of the app that issued the notification. This is something I can't hide because it's done by OS X. Sorry can't do anything about it.
