### ISSUE TITLE
Uncaught exception: Fatal: Error: read ETIMEDOUT

### ISSUE THREAD

**Issue by andofrjando** [cgrossde/Pullover#61]
Open laptop this morning to be greeted by this Pullover exception:

    Sun Jul 17 2016 08:24:16 GMT+0800 (AWST)  ConnectionManager    'Device woke up after 5127s of sleep'
    Sun Jul 17 2016 08:24:16 GMT+0800 (AWST)  ConnectionManager    'Reconnect'
    Sun Jul 17 2016 08:24:16 GMT+0800 (AWST)  ConnectionManager    'fetchAndConnect'
    Sun Jul 17 2016 08:24:16 GMT+0800 (AWST)  PushoverRESTClient   'OpenClient.prototype.fetchNotifications'
    Sun Jul 17 2016 08:24:18 GMT+0800 (AWST)  ConnectionManager    'Received 1 notifications'
    Sun Jul 17 2016 08:24:18 GMT+0800 (AWST)  PushoverRESTClient   'OpenClient.prototype.acknowledgeNotification'
    Sun Jul 17 2016 08:24:18 GMT+0800 (AWST)  ConnectionManager    'Connect to WebSocket'
    Sun Jul 17 2016 08:24:20 GMT+0800 (AWST)  PushoverWSClient     'Connected'
    Sun Jul 17 2016 08:24:30 GMT+0800 (AWST)  PushoverWSClient     'Socket closed'
    Sun Jul 17 2016 08:24:41 GMT+0800 (AWST)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
    Sun Jul 17 2016 08:24:41 GMT+0800 (AWST)  Fatal                'Pullover v1.0.0'
    Sun Jul 17 2016 08:24:41 GMT+0800 (AWST)  Fatal                '=============== STACK ==============='
    Sun Jul 17 2016 08:24:41 GMT+0800 (AWST)  Fatal                'Error: read ETIMEDOUT
        at exports._errnoException (util.js:734:11)
        at TCP.onread (net.js:531:26)'
    Sun Jul 17 2016 08:24:41 GMT+0800 (AWST)  Fatal                '=============== Error Object ==============='
    Sun Jul 17 2016 08:24:41 GMT+0800 (AWST)  Fatal                '{
        stack: 'Error: read ETIMEDOUT
        at exports._errnoException (util.js:734:11)
        at TCP.onread (net.js:531:26)',
        message: 'read ETIMEDOUT',
        code: 'ETIMEDOUT',
        errno: 'ETIMEDOUT',
        syscall: 'read'
        }'
    Sun Jul 17 2016 08:24:41 GMT+0800 (AWST)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
    Sun Jul 17 2016 08:24:41 GMT+0800 (AWST)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
    Sun Jul 17 2016 08:24:41 GMT+0800 (AWST)  Fatal                'Pullover v1.0.0'
    Sun Jul 17 2016 08:24:41 GMT+0800 (AWST)  Fatal                '=============== STACK ==============='
    Sun Jul 17 2016 08:24:41 GMT+0800 (AWST)  Fatal                'Error: socket hang up
        at createHangUpError (_http_client.js:192:15)
        at TLSSocket.socketCloseListener (_http_client.js:224:23)
        at emitOne (events.js:80:20)
        at TLSSocket.emit (events.js:150:7)
        at TCP.close (net.js:457:12)'
    Sun Jul 17 2016 08:24:41 GMT+0800 (AWST)  Fatal                '=============== Error Object ==============='
    Sun Jul 17 2016 08:24:41 GMT+0800 (AWST)  Fatal                '{ stack: 'Error: socket hang up
        at createHangUpError (_http_client.js:192:15)
        at TLSSocket.socketCloseListener (_http_client.js:224:23)
        at emitOne (events.js:80:20)
        at TLSSocket.emit (events.js:150:7)
        at TCP.close (net.js:457:12)', message: 'socket hang up', code: 'ECONNRESET' }'
    Sun Jul 17 2016 08:24:41 GMT+0800 (AWST)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
    Sun Jul 17 2016 08:24:46 GMT+0800 (AWST)  PushoverWSClient     'Socket closed'
    Sun Jul 17 2016 08:25:12 GMT+0800 (AWST)  ConnectionManager    'Fetch failed - offline'   { [FetchNotificationsFailed: Fetch notification request failed]
        name: 'FetchNotificationsFailed',
        cause: { [Error: read ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'read' } }
    Sun Jul 17 2016 08:25:12 GMT+0800 (AWST)  ConnectionManager    'Offline'
    Sun Jul 17 2016 08:25:12 GMT+0800 (AWST)  PushoverWSClient     'Socket closed'
    Sun Jul 17 2016 08:25:42 GMT+0800 (AWST)  ConnectionManager    'Checking internet connection'
    Sun Jul 17 2016 08:25:43 GMT+0800 (AWST)  ConnectionManager    'We are online again'
    Sun Jul 17 2016 08:25:43 GMT+0800 (AWST)  ConnectionManager    'fetchAndConnect'
    Sun Jul 17 2016 08:25:43 GMT+0800 (AWST)  PushoverRESTClient   'OpenClient.prototype.fetchNotifications'
    Sun Jul 17 2016 08:25:44 GMT+0800 (AWST)  ConnectionManager    'Received 0 notifications'
    Sun Jul 17 2016 08:25:44 GMT+0800 (AWST)  ConnectionManager    'Connect to WebSocket'
    Sun Jul 17 2016 08:25:45 GMT+0800 (AWST)  PushoverWSClient     'Connected'

**Comment by cgrossde** [comment]
Hmm, I'm not sure why those exceptions are not caught. Please try the new 1.2.0-alpha which has updated dependencies and a notification history: https://github.com/cgrossde/Pullover/releases/tag/1.2.0-alpha.1

Please report back in issue #63 if you are still experiencing these problems with the 1.2.0-alpha.1 version.
