### ISSUE TITLE
Change the notification area icon on pending messages

### ISSUE THREAD

**Issue by marcopaganini** [cgrossde/Pullover#64]
It would be awesome if pullover changed the icon in the notification area on incoming messages (like web.telegram.org does). Without this, it's easy to miss notifications. A click on the icon would open the list of messages and clear the icon back to its original state.

**Comment by cgrossde** [comment]
Changing the tray icon should be possible: 

* https://github.com/nwjs/nw.js/wiki/tray#trayicon
* https://github.com/cgrossde/Pullover/blob/master/src/app/nw/Tray.js#L11

A notification history is planned but not implemented yet: #11 

Feel free to contribute a PR.

**Comment by cgrossde** [comment]
As of v1.2 there is a notification history: https://github.com/cgrossde/Pullover/releases/tag/1.2.0
Added your idea to the list of feature requests #85
