### ISSUE TITLE
Update to nw.js greater than 12.3

### ISSUE THREAD

**Issue by cgrossde** [cgrossde/Pullover#65]
Currently blocked by https://github.com/nwjs/nw.js/issues/4336

**Comment by Ore4444** [comment]
Not blocked by  nwjs/nw.js#4336 anymore

**Comment by cgrossde** [comment]
Just checked and you are right. Started work on upgrading dependencies.
Current blocker:

 - https://github.com/sindresorhus/got/pull/271

**Comment by cgrossde** [comment]
Update NW.js to v0.28: [1.3.0-alpha.1](https://github.com/cgrossde/Pullover/releases/tag/1.3.0-alpha.1)
