### ISSUE TITLE
Notification History

### ISSUE THREAD

**Issue by alitvak69** [cgrossde/Pullover#68]
Love and use your software.  I understand that I am not paying for your work and really appreciate what you are doing.  However, I believe current notification history feature is useless without.

1.  Limiting visible messages to 1 - 2 days 
2.  Making the rest of the history with expendable links and grouping by  something like 3-7 days, week, month,  etc.
3.  Regardless of #2 making notifications history searchable
4.  Be able to have an idea of how the messages stored (locally on device or some kind of server?) and cleanup the history or limit history to X amount of time so it remove old messages automatically.

These are just my suggestions, please don't take it as negative critic of your work.

**Comment by cgrossde** [comment]
Thanks for your input. I accidentally closed #11 which lists some of your ideas as TODOs for the next release. I added the rest of your suggestions there and will implement them given enough free time.

**Comment by cgrossde** [comment]
And of course all notifications are stored locally ;) The only server contacted by pullover are pushover.net and github.com (to check for updates)
