### ISSUE TITLE
Suggestion - Manual close notification

### ISSUE THREAD

**Issue by Mike981874** [cgrossde/Pullover#69]
Hi there,

I appreciate the work you've done, not sure where else to contact you so I'm posting this here.

Currently I use another application for desktop notifications (except now with Pullover) and notifications essentially stay up on my desktop until I close them with a tiny X button or click it, similar to this but without the X button for manual close.

My recommendation is to add an option in the settings to only close notifications once they are clicked or closed manually, or have the close time set to 60 minutes with a button to close the notification.

Thanks

**Comment by Mike981874** [comment]
Wow, sorry. Didn't even realize it currently had one. The color of it was too similar to the white background.

Thanks anyways :100:

**Comment by DriesS** [comment]
@Mike981874 which application are you using? We need this feature as well that notifications are closed upon click by the user.

**Comment by Mike981874** [comment]
@DriesS I quit using the third party Windows apps and just used the Pushover Chrome site ( https://client.pushover.net/ ), been using it for a long time now.
