### ISSUE TITLE
Fatal Error on a regular base (maybe related to sleeping a macbook)

### ISSUE THREAD

**Issue by Khoulaiz** [cgrossde/Pullover#71]
[pullover.1.TXT](https://github.com/cgrossde/Pullover/files/493808/pullover.1.TXT)
<img width="450" alt="screen shot 2016-09-26 at 20 02 49" src="https://cloud.githubusercontent.com/assets/894816/18845987/40818974-8424-11e6-9aaa-28effc403880.png">

newest mac os version (sierra) but happened with the version before, too

**Comment by cgrossde** [comment]
Will track this one in #63
