### ISSUE TITLE
Support for Internet Proxy

### ISSUE THREAD

**Issue by dmackinnon** [cgrossde/Pullover#74]
Would be great if there was support for an internet proxy. My office happens to use one and I love this app, but can't use it at work.

**Comment by cgrossde** [comment]
I currently don't have time to implement this. Feel free to submit a PR and reopen this issue. I also added this to the feature request issue #85 .

**Comment by dmackinnon** [comment]
Happy to buy some licenses if that helps move it to the top of the pile.

**Comment by cgrossde** [comment]
Feel free to reopen the issue and place a bounty on https://www.bountysource.com. This is a hobby for me, so money is not the motivation. But you might find someone through bounty source who wants to take a look at it.

My priority currently is #65

**Comment by cgrossde** [comment]
Did some research:
* http websockets do not work with proxies, encrypted websockets should work mit proxies, need to check if Pushover supports wss://
* Fetching notifications uses standard http requests, the library supports the HTTP_PROXY and HTTPS_PROXY system vars, you could try to set those
* is-online & is-reachable does not support proxies => signifikant changes needed to support proxies
