### ISSUE TITLE
Priority = 2

### ISSUE THREAD

**Issue by Janatbek** [cgrossde/Pullover#81]
I have a pullover installed on my machine,
when I was testing pushover I put priority= 2, retry = 60 and expire = 3600.

now I am getting notifications every 60 seconds on pullover.

how to stop it?

**Comment by cgrossde** [comment]
Please be a little bit more detailed in your bug report. I can't follow your description of the bug.

**Comment by cgrossde** [comment]
Closing this, reopen if necessary.
