### ISSUE TITLE
Windows notification not persistent in Action Centre

### ISSUE THREAD

**Issue by joshwarren** [cgrossde/Pullover#84]
The notification appears in the Action Centre while when popup if visible only. Once the popup disappears, the notification in the Action Centre is also closed. My understanding of Microsoft's strategy with the Action Centre was that it was that notification would remain persistent there after a popup had closed: indeed that is the way that all my other programs and apps work. I have checked that 'Show notification in Action Centre' is On for pullover and that pullover is set to use native notifications. I'm afraid digging into the use of the Windows notification APIs is far beyond my abilities! 

This may be relevant: https://github.com/streamlink/streamlink-twitch-gui/issues/290 

Josh

**Comment by cgrossde** [comment]
I currently do not give support for Windows or its Action Center. If you want to see past notifications use the notification list provided by the app. However I would be happy to accept a PR that fixes the issue.

**Comment by cgrossde** [comment]
Feel free to submit a PR and reopen this issue. I also added this to the bugs/features waiting for PR issue #85.
