### ISSUE TITLE
Feature Request: Click on the notification to open app

### ISSUE THREAD

**Issue by zin105** [cgrossde/Pullover#87]
When a new notification shows up it would be great if when clicking it, the app would open.

**Comment by cgrossde** [comment]
Hmm, a notification could have a URL attached. Clicking on the notification would open the URL of the notification an not the app. This would be inconsistent behaviour. However I though about showing the notification list on clicking the tray icon.

**Comment by cgrossde** [comment]
Will keep the default behaviour for now.
