### ISSUE TITLE
Tray icon dropdown contains blank item at top

### ISSUE THREAD

**Issue by andrewdmcleod** [cgrossde/Pullover#90]
Dropdown (can't screenshot?) looks like:

.----------------------------------------.
|
| Status
| Notifications
|
| Quit Pullover
|
`-----------------------------------------'

If I click on the top blank "item" it takes me to whatever the last tab selected was (status, settings, etc)

**Comment by cgrossde** [comment]
Please try the new alpha if the problem is fixed there: [1.3.0-alpha.1](https://github.com/cgrossde/Pullover/releases/tag/1.3.0-alpha.1)
If not please reopen this issue ;)
