### ISSUE TITLE
Does not automatically reconnect on network loss

### ISSUE THREAD

**Issue by mostlychris** [cgrossde/Pullover#91]
Pullover does not automatically connect once network loss happens. If I close the app and reopen it, it will connect. The logs show it try to find a network connection but doesn't seem to, even though I've confirmed that I have network/internet access.

[pullover.2.log.docx](https://github.com/cgrossde/Pullover/files/952418/pullover.2.log.docx)

**Comment by cgrossde** [comment]
Please only attach txt or log files. Feel free to reopen ;)

**Comment by mostlychris** [comment]
Here is the same log file in txt format.


[pullover2.txt](https://github.com/cgrossde/Pullover/files/983738/pullover2.txt)
