### ISSUE TITLE
Building error with Linux

### ISSUE THREAD

**Issue by palytsh** [cgrossde/Pullover#93]
Hello!
There is error on Linux at the 1st step:

[root@nodejs pullover]# npm install
npm WARN deprecated swig@1.4.2: This package is no longer maintained

npm ERR! Linux 3.10.0-327.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for appdmg@0.4.5: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

**Comment by cgrossde** [comment]
As mentioned in the previous ticket you can only build for Windows and Linux on Linux not OS X aka Darwin. Adapt your buildConf.json to not include OS X.

**Comment by palytsh** [comment]
buildConf.json adapted. The same error.
