### ISSUE TITLE
Pullover doesn't reconnect after network loss.

### ISSUE THREAD

**Issue by mostlychris** [cgrossde/Pullover#94]
Pullover does not automatically connect once network loss happens. If I close the app and reopen it, it will connect. The logs show it try to find a network connection but doesn't seem to, even though I've confirmed that I have network/internet access.

[pullover2.txt](https://github.com/cgrossde/Pullover/files/983751/pullover2.txt)

Ref: #91

**Comment by cgrossde** [comment]
Pullover seems unable to detect if you have a internet connection. I think you are behind some kind of firewall. I don't have the ressources to look into this, sorry.
