### ISSUE TITLE
Error with Pullover 1.2.0

### ISSUE THREAD

**Issue by rafaelmagic** [cgrossde/Pullover#95]
Tue May 09 2017 21:46:21 GMT-0700 (Pacific Daylight Time)  Settings             'Settings loaded'   { windowWidth: 450,
  windowHeight: 330,
  displayTime: 7,
  nativeNotifications: false,
  maxNotificationAmount: 20,
  runOnStartup: true,
  defaultSound: 'po' }
Tue May 09 2017 21:46:22 GMT-0700 (Pacific Daylight Time)  NotificationManager   'maxNotificationAmount'   20
Tue May 09 2017 21:46:22 GMT-0700 (Pacific Daylight Time)  ConnectionManager    'fetchAndConnect'
Tue May 09 2017 21:46:22 GMT-0700 (Pacific Daylight Time)  PushoverRESTClient   'OpenClient.prototype.fetchNotifications'
Tue May 09 2017 21:46:22 GMT-0700 (Pacific Daylight Time)  UpdateCheck          'Check for update'
Tue May 09 2017 21:46:22 GMT-0700 (Pacific Daylight Time)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Tue May 09 2017 21:46:22 GMT-0700 (Pacific Daylight Time)  Fatal                'Pullover v1.2.0'
Tue May 09 2017 21:46:22 GMT-0700 (Pacific Daylight Time)  Fatal                '=============== STACK ==============='
Tue May 09 2017 21:46:22 GMT-0700 (Pacific Daylight Time)  Fatal                'Error: spawn cmd ENOENT
    at exports._errnoException (util.js:734:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1022:32)
    at child_process.js:1115:20
    at process._tickCallback (node.js:375:11)'
Tue May 09 2017 21:46:22 GMT-0700 (Pacific Daylight Time)  Fatal                '=============== Error Object ==============='
Tue May 09 2017 21:46:22 GMT-0700 (Pacific Daylight Time)  Fatal                '{
    stack: 'Error: spawn cmd ENOENT
    at exports._errnoException (util.js:734:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1022:32)
    at child_process.js:1115:20
    at process._tickCallback (node.js:375:11)',
    message: 'spawn cmd ENOENT',
    code: 'ENOENT',
    errno: 'ENOENT',
    syscall: 'spawn cmd',
    path: 'cmd',
    spawnargs: [
        '/C',
        'REG',
        'QUERY',
        'HKEY_CURRENT_USERSoftwareMicrosoftWindowsCurrentVersionRun',
        '/v',
        'Pullover'
    ]
}'
Tue May 09 2017 21:46:22 GMT-0700 (Pacific Daylight Time)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Tue May 09 2017 21:46:22 GMT-0700 (Pacific Daylight Time)  UpdateCheck          'No update available'   '1.2.0'
Tue May 09 2017 21:46:23 GMT-0700 (Pacific Daylight Time)  ConnectionManager    'Received 0 notifications'
Tue May 09 2017 21:46:23 GMT-0700 (Pacific Daylight Time)  ConnectionManager    'Connect to WebSocket'
Tue May 09 2017 21:46:23 GMT-0700 (Pacific Daylight Time)  PushoverWSClient     'Connected'

**Comment by cgrossde** [comment]
He seemed to miss the cmd.exe on you computer. Will close this for now, don't know what to do about it.
