### ISSUE TITLE
Fatal Error Occurred (Pullover 1.2.0 on OS X 10.7.5)

### ISSUE THREAD

**Issue by fogelfish** [cgrossde/Pullover#97]
Sorry I can't provide additional context to help make sense of this issue. I'm not sure if it happens only on system start or randomly after Pullover has already been running a while. It's happened a number of times over the last few weeks.  Thank you!

[pullover.1.log.zip](https://github.com/cgrossde/Pullover/files/1048395/pullover.1.log.zip)

**Comment by cgrossde** [comment]
Thanks for reporting. I will track it with the other crashes.
