### ISSUE TITLE
Windows installer does not work

### ISSUE THREAD

**Issue by jangxx** [cgrossde/Pullover#99]
Upon running the 1.2.0 installer, I get a message box saying this:

    NSIS Error
    ---------------------------
    Installer integrity check has failed. Common causes include
    incomplete download and damaged media. Contact the
    installer's author to obtain a new copy.
    
    More information at:
    http://nsis.sf.net/NSIS_Error

I could not find anything useful on this issue and redownloading, renaming the installer exe and even running it with a `/NCRC` parameter did not fix this issue.

I'm running the Windows 10 x64 Creators Update.

**Comment by cgrossde** [comment]
Please try the new alpha: [1.3.0-alpha.1](https://github.com/cgrossde/Pullover/releases/tag/1.3.0-alpha.1)
If the issue persists, feel free to reopen this issue ;)
